name: API workflow

on: 
  push:
    branches:
      - main  # Adjust this to your main branch name if needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Python API
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Specify the Python version you are using

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests and collect coverage
        run: pytest --cov .

      - name: Upload coverage reports to Codecov
        if: success()  # Only upload if tests pass
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --verbose --token=${{ secrets.CODECOV_TOKEN }} --file coverage-service.xml
